# BitcoinMining Configuration

# Mining Settings
mining-difficulty: 1.0
max-rigs-per-player: 5

# Bitcoin Transfer Settings
transfer-fee: 0.01
min-transfer-amount: 0.00000001

# Price Update Settings
price-update-interval: 60
price-api-timeout: 5

# Leaderboard Settings
leaderboard-size: 10
leaderboard-update-interval: 300

# Database Settings
database-save-interval: 300

# Daily Reset Settings
reset-daily-profits: true
reset-time: "00:00"

# Hologram Settings
enable-holograms: true
hologram-update-interval: 20 # In ticks (20 = 1 second)

# Particle Effects
enable-particles: true
particle-chance: 0.1

# Sound Effects
enable-sounds: true
sound-chance: 0.05

# Debug Mode
debug: false

# Black Market Settings
black-market:
  always-open: true
  time-range: "21:00-22:00"
  default-stock: 10
  items:
    example_diamond:
      material: DIAMOND
      amount: 10
      price-usd: 50000.0
      max-stock: 5
      display-name: "§b§lSpecial Diamonds"
      lore:
        - "§7Rare diamonds from the"
        - "§7depths of the Bitcoin mines!"

# Mining Rig Levels (with balanced costs)
rig-levels:
  level-1:
    display-name: "§6Mining Rig §7[§eLevel 1§7]"
    hash-rate: 0.001
    fuel-capacity: 64
    fuel-consumption: 1.0
    cost: 1000.0
    upgrade-cost: 0.05
  level-2:
    display-name: "§6Mining Rig §7[§eLevel 2§7]"
    hash-rate: 0.0025
    fuel-capacity: 96
    fuel-consumption: 0.98
    cost: 2500.0
    upgrade-cost: 0.125
  level-3:
    display-name: "§6Mining Rig §7[§eLevel 3§7]"
    hash-rate: 0.004
    fuel-capacity: 128
    fuel-consumption: 0.96
    cost: 5000.0
    upgrade-cost: 0.2
  level-4:
    display-name: "§6Mining Rig §7[§eLevel 4§7]"
    hash-rate: 0.006
    fuel-capacity: 160
    fuel-consumption: 0.94
    cost: 10000.0
    upgrade-cost: 0.3
  level-5:
    display-name: "§6Mining Rig §7[§eLevel 5§7]"
    hash-rate: 0.009
    fuel-capacity: 192
    fuel-consumption: 0.92
    cost: 20000.0
    upgrade-cost: 0.45
  level-6:
    display-name: "§6Mining Rig §7[§eLevel 6§7]"
    hash-rate: 0.013
    fuel-capacity: 224
    fuel-consumption: 0.90
    cost: 35000.0
    upgrade-cost: 0.65
  level-7:
    display-name: "§6Mining Rig §7[§eLevel 7§7]"
    hash-rate: 0.018
    fuel-capacity: 256
    fuel-consumption: 0.88
    cost: 55000.0
    upgrade-cost: 0.9
  level-8:
    display-name: "§6Mining Rig §7[§eLevel 8§7]"
    hash-rate: 0.025
    fuel-capacity: 288
    fuel-consumption: 0.86
    cost: 80000.0
    upgrade-cost: 1.25
  level-9:
    display-name: "§6Mining Rig §7[§eLevel 9§7]"
    hash-rate: 0.034
    fuel-capacity: 320
    fuel-consumption: 0.84
    cost: 120000.0
    upgrade-cost: 1.7
  level-10:
    display-name: "§6Mining Rig §7[§eLevel 10§7]"
    hash-rate: 0.045
    fuel-capacity: 352
    fuel-consumption: 0.82
    cost: 175000.0
    upgrade-cost: 2.25
  level-11:
    display-name: "§6Mining Rig §7[§eLevel 11§7]"
    hash-rate: 0.06
    fuel-capacity: 384
    fuel-consumption: 0.80
    cost: 250000.0
    upgrade-cost: 3.0
  level-12:
    display-name: "§6Mining Rig §7[§eLevel 12§7]"
    hash-rate: 0.08
    fuel-capacity: 416
    fuel-consumption: 0.78
    cost: 350000.0
    upgrade-cost: 4.0
  level-13:
    display-name: "§6Mining Rig §7[§eLevel 13§7]"
    hash-rate: 0.105
    fuel-capacity: 448
    fuel-consumption: 0.76
    cost: 500000.0
    upgrade-cost: 5.25
  level-14:
    display-name: "§6Mining Rig §7[§eLevel 14§7]"
    hash-rate: 0.135
    fuel-capacity: 480
    fuel-consumption: 0.74
    cost: 700000.0
    upgrade-cost: 6.75
  level-15:
    display-name: "§6Mining Rig §7[§eLevel 15§7]"
    hash-rate: 0.17
    fuel-capacity: 512
    fuel-consumption: 0.72
    cost: 1000000.0
    upgrade-cost: 8.5
  level-16:
    display-name: "§6Mining Rig §7[§eLevel 16§7]"
    hash-rate: 0.22
    fuel-capacity: 576
    fuel-consumption: 0.70
    cost: 1400000.0
    upgrade-cost: 11.0
  level-17:
    display-name: "§6Mining Rig §7[§eLevel 17§7]"
    hash-rate: 0.28
    fuel-capacity: 640
    fuel-consumption: 0.68
    cost: 2000000.0
    upgrade-cost: 14.0
  level-18:
    display-name: "§6Mining Rig §7[§eLevel 18§7]"
    hash-rate: 0.35
    fuel-capacity: 704
    fuel-consumption: 0.66
    cost: 2800000.0
    upgrade-cost: 17.5
  level-19:
    display-name: "§6Mining Rig §7[§eLevel 19§7]"
    hash-rate: 0.45
    fuel-capacity: 768
    fuel-consumption: 0.64
    cost: 4000000.0
    upgrade-cost: 22.5
  level-20:
    display-name: "§6§lMining Rig §7[§e§lLevel 20 - MAX§7]"
    hash-rate: 0.6
    fuel-capacity: 1024
    fuel-consumption: 0.60
    cost: 6000000.0
    upgrade-cost: -1