name: BitcoinMining
version: '1.0'
main: com.Lino.bitcoinMining.BitcoinMining
api-version: 1.21
author: Lino
depend:
  - Vault
description: A Bitcoin mining simulation plugin for Spigot

commands:
  bitcoin:
    description: Main command for Bitcoin operations
    usage: /bitcoin
    aliases: [btc]
    permission: bitcoinmining.use

  btctransfer:
    description: Transfer Bitcoin to another player
    usage: /btctransfer <player> <amount>
    permission: bitcoinmining.transfer

  btcconvert:
    description: Convert between Bitcoin and server economy
    usage: /btcconvert <to|from> <amount>
    permission: bitcoinmining.convert

  miner:
    description: Manage mining rigs
    usage: /miner
    permission: bitcoinmining.miner

  btctop:
    description: Show top Bitcoin miners leaderboard
    usage: /btctop
    aliases: [btcleaderboard]
    permission: bitcoinmining.leaderboard

permissions:
  bitcoinmining.use:
    description: Basic permission to use Bitcoin commands
    default: true

  bitcoinmining.transfer:
    description: Permission to transfer Bitcoin to others
    default: true

  bitcoinmining.convert:
    description: Permission to convert between Bitcoin and server currency
    default: true

  bitcoinmining.miner:
    description: Permission to manage mining rigs
    default: true

  bitcoinmining.leaderboard:
    description: Permission to view Bitcoin leaderboard
    default: true

  bitcoinmining.place:
    description: Permission to place mining rigs
    default: true

  bitcoinmining.break:
    description: Permission to break mining rigs
    default: true

  bitcoinmining.admin:
    description: Admin permission for BitcoinMining plugin
    default: op

  bitcoinmining.*:
    description: All BitcoinMining permissions
    default: op
    children:
      bitcoinmining.use: true
      bitcoinmining.transfer: true
      bitcoinmining.convert: true
      bitcoinmining.miner: true
      bitcoinmining.leaderboard: true
      bitcoinmining.place: true
      bitcoinmining.break: true
      bitcoinmining.admin: true